name       : klystrack
homepage   : http://kometbomb.github.io/klystrack/
version    : 1.7.3
release    : 1
source     :
    - git|https://github.com/kometbomb/klystrack.git : 954944e0834718b7d015ec951d7eafd9ef5e0ff3
    - git|https://github.com/kometbomb/klystron.git : 2a3d88d0d602b659cc896883ac346bae216b84d5
license    : MIT
component  : multimedia.audio
summary    : A chiptune tracker
description: |
    Klystrack is a chiptune tracker for making chiptune-like music on a modern computer.
builddeps  :
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
setup      : |
    cp -a $sources/klystron.git ../klystron
    touch src/version.h
    touch ../klystron/src/version.h
build      : |
    %make
install    : |
    # Ported from linux/Makefile (which is effectively broken)
    install -D -m 00755 bin.debug/klystrack $installdir/usr/bin/klystrack

    # Resources
    install -D -d -m 00755 $installdir/%libdir%/klystrack/{res,key,examples}
    install -m 00644 res/* $installdir/%libdir%/klystrack/res/.
    install -m 00644 key/* $installdir/%libdir%/klystrack/key/.
    cp -a examples/* $installdir/%libdir%/klystrack/examples/.

    install -D -m 00644 LICENSE $installdir/usr/share/doc/klystrack/LICENSE

    # Finally sort out the desktop file
    install -D -m 00644 icon/256x256.png $installdir/usr/share/pixmaps/klystrack.png
    install -D -m 00644 $pkgfiles/klystrack.desktop $installdir/usr/share/applications/klystrack.desktop
