name       : klystrack
homepage   : http://kometbomb.github.io/klystrack/
version    : 1.7.6
release    : 4
source     :
    - git|https://github.com/kometbomb/klystrack.git : 41a506e384ef68f738a8446dc09aa3f30055cbde
    - git|https://github.com/kometbomb/klystron.git : f5332ab4614cbb2f8b44c4e190a15d1afe741750
license    : MIT
component  : multimedia.audio
summary    : A chiptune tracker
description: |
    Klystrack is a chiptune tracker for making chiptune-like music on a modern computer.
builddeps  :
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
setup      : |
    cp -a $sources/klystron.git ../klystron
    touch src/version.h
    touch ../klystron/src/version.h
build      : |
    %make
install    : |
    # Ported from linux/Makefile (which is effectively broken)
    install -D -m 00755 bin.debug/klystrack $installdir/usr/bin/klystrack

    # Resources
    install -D -d -m 00755 $installdir/%libdir%/klystrack/{res,key,examples}
    install -m 00644 res/* $installdir/%libdir%/klystrack/res/.
    install -m 00644 key/* $installdir/%libdir%/klystrack/key/.
    cp -a examples/* $installdir/%libdir%/klystrack/examples/.

    install -D -m 00644 LICENSE $installdir/usr/share/doc/klystrack/LICENSE

    # Finally sort out the desktop file
    install -D -m 00644 icon/256x256.png $installdir/usr/share/pixmaps/klystrack.png
    install -D -m 00644 $pkgfiles/klystrack.desktop $installdir/usr/share/applications/klystrack.desktop
